### ISSUE TITLE
Pulling incorrect times from excel ground commitments

### ISSUE THREAD

**Issue by 18AGRS** [ryan-d-williams/Gonkulator_Issues#22]
![Excel commitment](https://user-images.githubusercontent.com/85189780/121261918-cfe0da00-c85f-11eb-9725-a16afbbc8974.PNG)

**Comment by ryan-d-williams** [comment]
@18AGRS fixed

**Comment by ryan-d-williams** [comment]
https://github.com/ryan-d-williams/77thScheduling/pull/249
