### ISSUE TITLE
Merge commitments feature - (PEX to Gonk) - 27FS Langley

### ISSUE THREAD

**Issue by jmaxyon** [ryan-d-williams/Gonkulator_Issues#56]
Wizard,

I sent you a personal email of our formatted excel file for commitments pulled from PEX as well as texted you about this. I've also attached the file here. Just looking to be able to better utilize the merge commitments feature since I don't think our format is currently supported. Thanks for the help. 

-Cray Yo
[ExportedReport.xlsx](https://github.com/ryan-d-williams/Gonkulator_Issues/files/9010588/ExportedReport.xlsx)
n

**Comment by ryan-d-williams** [comment]
Sorry I forgot to update this. This should be good to go now, feel free to reopen if not!
