### ISSUE TITLE
Schedule View-Only Link Not Working

### ISSUE THREAD

**Issue by timmann2** [ryan-d-williams/Gonkulator_Issues#57]
119FS (Atlantic City) - after selecting a date range or one of the quick buttons for this week, next week, etc., the following page is blank except for a list of pilot names on the left.

**Comment by ryan-d-williams** [comment]
Fixed!

**Comment by ryan-d-williams** [comment]
https://github.com/ryan-d-williams/77thScheduling/issues/484
